### ISSUE TITLE
Upgrade from version prior to Tutor

### ISSUE THREAD

**Issue by roblhibbard** [regisb/tutor#109]
What is the best way to update from the previous openedx platform before the update to tutor. I did an an make update on previous version and now my platform will not load. I then discovered the migration to Tutor.

thank you,

Robert

**Comment by regisb** [comment]
Please follow these steps:

1. `git pull`
2. `make upgrade-to-tutor`
3. `cd deploy/local && make update`

You should now have the newest docker images. Can you please confirm if it's working? I should probably add this to the documentation.

**Comment by roblhibbard** [comment]
Should the previous database also transfer? If so, mine did not. If I try and logon to studio.hibbardsclass.org this is the result.

 

<pre>

nginx_1_777880ca9fd3 | 2018/12/28 15:46:37 [warn] 8#8: *29 upstream sent more data than specified in "Content-Length" header while reading upstream, client: 184.155.240.3, server: studio.localhost, request: "GET / HTTP/1.1", upstream: "http://172.19.0.11:8000/", host: "studio.hibbardsclass.org"

nginx_1_777880ca9fd3 | 184.155.240.3 - - [28/Dec/2018:15:46:37 +0000] "GET / HTTP/1.1" 500 135 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36" "-"

cms_1_8b3d967690a7 |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 143, in handle_uncaught_exception

cms_1_8b3d967690a7 |     return callback(request, **param_dict)

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/common/djangoapps/util/views.py", line 102, in wrapper

cms_1_8b3d967690a7 |     return func(request, *args, **kwargs)

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/cms/djangoapps/contentstore/views/error.py", line 27, in inner

cms_1_8b3d967690a7 |     return func(request, *args, **kwargs)

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/cms/djangoapps/contentstore/views/error.py", line 51, in render_500

cms_1_8b3d967690a7 |     return HttpResponseServerError(render_to_string('500.html', {}, request=request))

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 159, in render_to_string

cms_1_8b3d967690a7 |     return template.render(dictionary, request)

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/common/djangoapps/edxmako/template.py", line 59, in render

cms_1_8b3d967690a7 |     return self.mako_template.render_unicode(**context_dictionary)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/mako/template.py", line 454, in render_unicode

cms_1_8b3d967690a7 |     as_unicode=True)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 829, in _render

cms_1_8b3d967690a7 |     **_kwargs_for_callable(callable_, data))

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 864, in _render_context

cms_1_8b3d967690a7 |     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 890, in _exec_template

cms_1_8b3d967690a7 |     callable_(context, *args, **kwargs)

cms_1_8b3d967690a7 |   File "/tmp/mako_cms/dc85de2a75159713fe2f6012af583eca/base.html.py", line 217, in render_body

cms_1_8b3d967690a7 |     __M_writer(filters.html_escape(filters.decode.utf8(static.webpack(entry=u'commons'))))

cms_1_8b3d967690a7 |   File "/tmp/mako_cms/dc85de2a75159713fe2f6012af583eca/static_content.html.py", line 288, in render_webpack

cms_1_8b3d967690a7 |     __M_writer(filters.html_escape(filters.decode.utf8(HTML(render_bundle(entry, extension=None, config='DEFAULT', attrs=attrs)))))

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/templatetags/webpack_loader.py", line 12, in render_bundle

cms_1_8b3d967690a7 |     tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/utils.py", line 45, in get_as_tags

cms_1_8b3d967690a7 |     bundle = _get_bundle(bundle_name, extension, config)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/utils.py", line 23, in _get_bundle

cms_1_8b3d967690a7 |     bundle = get_loader(config).get_bundle(bundle_name)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/loader.py", line 60, in get_bundle

cms_1_8b3d967690a7 |     assets = self.get_assets()

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/loader.py", line 37, in get_assets

cms_1_8b3d967690a7 |     self._assets[self.name] = self._load_assets()

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/loader.py", line 32, in _load_assets

cms_1_8b3d967690a7 |     self.config['STATS_FILE']))

cms_1_8b3d967690a7 | IOError: Error reading /openedx/staticfiles/studio/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?

cms_1_8b3d967690a7 | 2018-12-28 15:46:58,691 INFO 120 [tracking] logger.py:50 - {"username": "", "event_type": "/", "ip": "184.155.240.3", "agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36", "host": "studio.hibbardsclass.org", "referer": "", "accept_language": "en-US,en;q=0.9", "event": "{\"POST\": {}, \"GET\": {}}", "event_source": "server", "context": {"user_id": null, "org_id": "", "course_id": "", "path": "/"}, "time": "2018-12-28T15:46:58.691425+00:00", "page": null}

cms_1_8b3d967690a7 | 2018-12-28 15:46:58,706 ERROR 120 [root] signals.py:17 - Uncaught exception from None

cms_1_8b3d967690a7 | Traceback (most recent call last):

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner

cms_1_8b3d967690a7 |     response = get_response(request)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response

cms_1_8b3d967690a7 |     response = self._get_response(request)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response

cms_1_8b3d967690a7 |     response = self.process_exception_by_middleware(e, request)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response

cms_1_8b3d967690a7 |     response = wrapped_callback(request, *callback_args, **callback_kwargs)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 185, in inner

cms_1_8b3d967690a7 |     return func(*args, **kwargs)

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/cms/djangoapps/contentstore/views/public.py", line 74, in howitworks

cms_1_8b3d967690a7 |     return render_to_response('howitworks.html', {})

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 169, in render_to_response

cms_1_8b3d967690a7 |     return HttpResponse(render_to_string(template_name, dictionary, namespace, request), **kwargs)

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 159, in render_to_string

cms_1_8b3d967690a7 |     return template.render(dictionary, request)

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/common/djangoapps/edxmako/template.py", line 59, in render

cms_1_8b3d967690a7 |     return self.mako_template.render_unicode(**context_dictionary)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/mako/template.py", line 454, in render_unicode

cms_1_8b3d967690a7 |     as_unicode=True)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 829, in _render

cms_1_8b3d967690a7 |     **_kwargs_for_callable(callable_, data))

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 864, in _render_context

cms_1_8b3d967690a7 |     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 890, in _exec_template

cms_1_8b3d967690a7 |     callable_(context, *args, **kwargs)

cms_1_8b3d967690a7 |   File "/tmp/mako_cms/dc85de2a75159713fe2f6012af583eca/base.html.py", line 217, in render_body

cms_1_8b3d967690a7 |     __M_writer(filters.html_escape(filters.decode.utf8(static.webpack(entry=u'commons'))))

cms_1_8b3d967690a7 |   File "/tmp/mako_cms/dc85de2a75159713fe2f6012af583eca/static_content.html.py", line 288, in render_webpack

cms_1_8b3d967690a7 |     __M_writer(filters.html_escape(filters.decode.utf8(HTML(render_bundle(entry, extension=None, config='DEFAULT', attrs=attrs)))))

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/templatetags/webpack_loader.py", line 12, in render_bundle

cms_1_8b3d967690a7 |     tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/utils.py", line 45, in get_as_tags

cms_1_8b3d967690a7 |     bundle = _get_bundle(bundle_name, extension, config)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/utils.py", line 23, in _get_bundle

cms_1_8b3d967690a7 |     bundle = get_loader(config).get_bundle(bundle_name)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/loader.py", line 60, in get_bundle

cms_1_8b3d967690a7 |     assets = self.get_assets()

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/loader.py", line 37, in get_assets

cms_1_8b3d967690a7 |     self._assets[self.name] = self._load_assets()

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/loader.py", line 32, in _load_assets

cms_1_8b3d967690a7 |     self.config['STATS_FILE']))

cms_1_8b3d967690a7 | IOError: Error reading /openedx/staticfiles/studio/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?

cms_1_8b3d967690a7 | 2018-12-28 15:46:58,707 ERROR 120 [django.request] exception.py:135 - Internal Server Error: /

cms_1_8b3d967690a7 | Traceback (most recent call last):

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner

cms_1_8b3d967690a7 |     response = get_response(request)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response

cms_1_8b3d967690a7 |     response = self._get_response(request)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response

cms_1_8b3d967690a7 |     response = self.process_exception_by_middleware(e, request)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response

cms_1_8b3d967690a7 |     response = wrapped_callback(request, *callback_args, **callback_kwargs)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 185, in inner

cms_1_8b3d967690a7 |     return func(*args, **kwargs)

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/cms/djangoapps/contentstore/views/public.py", line 74, in howitworks

cms_1_8b3d967690a7 |     return render_to_response('howitworks.html', {})

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 169, in render_to_response

cms_1_8b3d967690a7 |     return HttpResponse(render_to_string(template_name, dictionary, namespace, request), **kwargs)

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 159, in render_to_string

cms_1_8b3d967690a7 |     return template.render(dictionary, request)

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/common/djangoapps/edxmako/template.py", line 59, in render

cms_1_8b3d967690a7 |     return self.mako_template.render_unicode(**context_dictionary)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/mako/template.py", line 454, in render_unicode

cms_1_8b3d967690a7 |     as_unicode=True)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 829, in _render

cms_1_8b3d967690a7 |     **_kwargs_for_callable(callable_, data))

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 864, in _render_context

cms_1_8b3d967690a7 |     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 890, in _exec_template

cms_1_8b3d967690a7 |     callable_(context, *args, **kwargs)

cms_1_8b3d967690a7 |   File "/tmp/mako_cms/dc85de2a75159713fe2f6012af583eca/base.html.py", line 217, in render_body

cms_1_8b3d967690a7 |     __M_writer(filters.html_escape(filters.decode.utf8(static.webpack(entry=u'commons'))))

cms_1_8b3d967690a7 |   File "/tmp/mako_cms/dc85de2a75159713fe2f6012af583eca/static_content.html.py", line 288, in render_webpack

cms_1_8b3d967690a7 |     __M_writer(filters.html_escape(filters.decode.utf8(HTML(render_bundle(entry, extension=None, config='DEFAULT', attrs=attrs)))))

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/templatetags/webpack_loader.py", line 12, in render_bundle

cms_1_8b3d967690a7 |     tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/utils.py", line 45, in get_as_tags

cms_1_8b3d967690a7 |     bundle = _get_bundle(bundle_name, extension, config)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/utils.py", line 23, in _get_bundle

cms_1_8b3d967690a7 |     bundle = get_loader(config).get_bundle(bundle_name)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/loader.py", line 60, in get_bundle

cms_1_8b3d967690a7 |     assets = self.get_assets()

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/loader.py", line 37, in get_assets

cms_1_8b3d967690a7 |     self._assets[self.name] = self._load_assets()

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/loader.py", line 32, in _load_assets

cms_1_8b3d967690a7 |     self.config['STATS_FILE']))

cms_1_8b3d967690a7 | IOError: Error reading /openedx/staticfiles/studio/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?

cms_1_8b3d967690a7 | 2018-12-28 15:46:58 [120] [ERROR] Error handling request

cms_1_8b3d967690a7 | Traceback (most recent call last):

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 126, in handle_request

cms_1_8b3d967690a7 |     respiter = self.wsgi(environ, resp.start_response)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 157, in __call__

cms_1_8b3d967690a7 |     response = self.get_response(request)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 124, in get_response

cms_1_8b3d967690a7 |     response = self._middleware_chain(request)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 43, in inner

cms_1_8b3d967690a7 |     response = response_for_exception(request, exc)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 93, in response_for_exception

cms_1_8b3d967690a7 |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 143, in handle_uncaught_exception

cms_1_8b3d967690a7 |     return callback(request, **param_dict)

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/common/djangoapps/util/views.py", line 102, in wrapper

cms_1_8b3d967690a7 |     return func(request, *args, **kwargs)

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/cms/djangoapps/contentstore/views/error.py", line 27, in inner

cms_1_8b3d967690a7 |     return func(request, *args, **kwargs)

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/cms/djangoapps/contentstore/views/error.py", line 51, in render_500

cms_1_8b3d967690a7 |     return HttpResponseServerError(render_to_string('500.html', {}, request=request))

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 159, in render_to_string

cms_1_8b3d967690a7 |     return template.render(dictionary, request)

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/common/djangoapps/edxmako/template.py", line 59, in render

cms_1_8b3d967690a7 |     return self.mako_template.render_unicode(**context_dictionary)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/mako/template.py", line 454, in render_unicode

cms_1_8b3d967690a7 |     as_unicode=True)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 829, in _render

cms_1_8b3d967690a7 |     **_kwargs_for_callable(callable_, data))

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 864, in _render_context

cms_1_8b3d967690a7 |     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 890, in _exec_template

cms_1_8b3d967690a7 |     callable_(context, *args, **kwargs)

cms_1_8b3d967690a7 |   File "/tmp/mako_cms/dc85de2a75159713fe2f6012af583eca/base.html.py", line 217, in render_body

cms_1_8b3d967690a7 |     __M_writer(filters.html_escape(filters.decode.utf8(static.webpack(entry=u'commons'))))

cms_1_8b3d967690a7 |   File "/tmp/mako_cms/dc85de2a75159713fe2f6012af583eca/static_content.html.py", line 288, in render_webpack

cms_1_8b3d967690a7 |     __M_writer(filters.html_escape(filters.decode.utf8(HTML(render_bundle(entry, extension=None, config='DEFAULT', attrs=attrs)))))

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/templatetags/webpack_loader.py", line 12, in render_bundle

cms_1_8b3d967690a7 |     tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/utils.py", line 45, in get_as_tags

cms_1_8b3d967690a7 |     bundle = _get_bundle(bundle_name, extension, config)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/utils.py", line 23, in _get_bundle

cms_1_8b3d967690a7 |     bundle = get_loader(config).get_bundle(bundle_name)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/loader.py", line 60, in get_bundle

cms_1_8b3d967690a7 |     assets = self.get_assets()

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/loader.py", line 37, in get_assets

cms_1_8b3d967690a7 |     self._assets[self.name] = self._load_assets()

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/loader.py", line 32, in _load_assets

cms_1_8b3d967690a7 |     self.config['STATS_FILE']))

cms_1_8b3d967690a7 | IOError: Error reading /openedx/staticfiles/studio/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?

cms_1_8b3d967690a7 | 2018-12-28 15:46:58,923 ERROR 120 [gunicorn.error] glogging.py:219 - Error handling request

cms_1_8b3d967690a7 | Traceback (most recent call last):

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 126, in handle_request

cms_1_8b3d967690a7 |     respiter = self.wsgi(environ, resp.start_response)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 157, in __call__

cms_1_8b3d967690a7 |     response = self.get_response(request)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 124, in get_response

cms_1_8b3d967690a7 |     response = self._middleware_chain(request)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 43, in inner

cms_1_8b3d967690a7 |     response = response_for_exception(request, exc)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 93, in response_for_exception

cms_1_8b3d967690a7 |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 143, in handle_uncaught_exception

cms_1_8b3d967690a7 |     return callback(request, **param_dict)

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/common/djangoapps/util/views.py", line 102, in wrapper

cms_1_8b3d967690a7 |     return func(request, *args, **kwargs)

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/cms/djangoapps/contentstore/views/error.py", line 27, in inner

cms_1_8b3d967690a7 |     return func(request, *args, **kwargs)

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/cms/djangoapps/contentstore/views/error.py", line 51, in render_500

cms_1_8b3d967690a7 |     return HttpResponseServerError(render_to_string('500.html', {}, request=request))

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 159, in render_to_string

cms_1_8b3d967690a7 |     return template.render(dictionary, request)

cms_1_8b3d967690a7 |   File "/openedx/edx-platform/common/djangoapps/edxmako/template.py", line 59, in render

cms_1_8b3d967690a7 |     return self.mako_template.render_unicode(**context_dictionary)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/mako/template.py", line 454, in render_unicode

cms_1_8b3d967690a7 |     as_unicode=True)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 829, in _render

cms_1_8b3d967690a7 |     **_kwargs_for_callable(callable_, data))

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 864, in _render_context

cms_1_8b3d967690a7 |     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/mako/runtime.py", line 890, in _exec_template

cms_1_8b3d967690a7 |     callable_(context, *args, **kwargs)

cms_1_8b3d967690a7 |   File "/tmp/mako_cms/dc85de2a75159713fe2f6012af583eca/base.html.py", line 217, in render_body

cms_1_8b3d967690a7 |     __M_writer(filters.html_escape(filters.decode.utf8(static.webpack(entry=u'commons'))))

cms_1_8b3d967690a7 |   File "/tmp/mako_cms/dc85de2a75159713fe2f6012af583eca/static_content.html.py", line 288, in render_webpack

cms_1_8b3d967690a7 |     __M_writer(filters.html_escape(filters.decode.utf8(HTML(render_bundle(entry, extension=None, config='DEFAULT', attrs=attrs)))))

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/templatetags/webpack_loader.py", line 12, in render_bundle

cms_1_8b3d967690a7 |     tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/utils.py", line 45, in get_as_tags

cms_1_8b3d967690a7 |     bundle = _get_bundle(bundle_name, extension, config)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/utils.py", line 23, in _get_bundle

cms_1_8b3d967690a7 |     bundle = get_loader(config).get_bundle(bundle_name)

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/loader.py", line 60, in get_bundle

cms_1_8b3d967690a7 |     assets = self.get_assets()

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/loader.py", line 37, in get_assets

cms_1_8b3d967690a7 |     self._assets[self.name] = self._load_assets()

cms_1_8b3d967690a7 |   File "/usr/local/lib/python2.7/dist-packages/webpack_loader/loader.py", line 32, in _load_assets

cms_1_8b3d967690a7 |     self.config['STATS_FILE']))

cms_1_8b3d967690a7 | IOError: Error reading /openedx/staticfiles/studio/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?

nginx_1_777880ca9fd3 | 184.155.240.3 - - [28/Dec/2018:15:46:58 +0000] "GET / HTTP/1.1" 500 135 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36" "-"

nginx_1_777880ca9fd3 | 2018/12/28 15:46:58 [warn] 8#8: *32 upstream sent more data than specified in "Content-Length" header while reading upstream, client: 184.155.240.3, server: studio.localhost, request: "GET / HTTP/1.1", upstream: "http://172.19.0.11:8000/", host: "studio.hibbardsclass.org"</pre>

 

I can log onto hibbardsclass.org just fine, but without previous database info.

 

Thank you,

 

Robert

**Comment by regisb** [comment]
@roblhibbard this seems to be the same issue as #111. I'm currently working on a fix.

**Comment by regisb** [comment]
Please wait a few minutes until the docker images are rebuilt, and then run:

```
make update
make assets
make restart-openedx
```

**Comment by roblhibbard** [comment]
How do I access the MongoDB? I would like to create a dump file. I tried using the user openedx and the password that is the same for mysql. I can connect fine to the mysql database but not the mongo.

 

Thank you,

 

Robert

**Comment by roblhibbard** [comment]
Good morning:

 

Disregard the last email I sent. I got it all figured out. My platform was so messed up that I just loaded the new one from scratch then imported my previous data. I was able to back up the mysql and mongoDB and import into the new one.

 

All seems to be working. I however noticed if I chose to opt in to the external grader that it would cause issues with the rest of the platform running. So I did a make configure and chose N on that option.

 

Hope you have a great start to the new year.

 

Robert

**Comment by roblhibbard** [comment]
Good morning,

 

Well it is still morning here in Nampa, Idaho anyways. It looks like when I pulled my databases back in, I did not change the passwords to match for the xqueue. Once I fixed that it did allow the platform to work. But here is the error log for the xqueue_consumer_1_ 

 

xqueue_consumer_1_fb4a514bcb7d | manage.py run_consumer: error: unrecognized arguments: 12

xqueue_consumer_1_fb4a514bcb7d | usage: manage.py run_consumer [-h] [--version] [-v {0,1,2,3}]

xqueue_consumer_1_fb4a514bcb7d |                               [--settings SETTINGS] [--pythonpath PYTHONPATH]

xqueue_consumer_1_fb4a514bcb7d |                               [--traceback] [--no-color]

xqueue_consumer_1_fb4a514bcb7d | manage.py run_consumer: error: unrecognized arguments: 12

 

local_xqueue_consumer_1_fb4a514bcb7d exited with code 2

 

also 

 

local_forum_1_8657079dc734 exited with code 1

 

I could be possible that I missed an authorization password or something. 

 

Info

uname -a

Linux hibbsedxbox 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

-------------------------

git rev-parse HEAD

65fd2114f84ec492a392588ce5fb4add247fa257

-------------------------

docker version

Client:

Version:           18.06.1-ce

API version:       1.38

Go version:        go1.10.3

Git commit:        e68fc7a

Built:             Tue Aug 21 17:24:56 2018

OS/Arch:           linux/amd64

Experimental:      false

 

Server:

Engine:

  Version:          18.06.1-ce

  API version:      1.38 (minimum version 1.12)

  Go version:       go1.10.3

  Git commit:       e68fc7a

  Built:            Tue Aug 21 17:23:21 2018

  OS/Arch:          linux/amd64

  Experimental:     false

-------------------------

docker-compose --version

docker-compose version 1.23.1, build b02f1306

-------------------------

echo $EDX_PLATFORM_PATH

 

echo $EDX_PLATFORM_SETTINGS

**Comment by regisb** [comment]
Hi @frohro! Nginx cannot bind to port 8443, so it's simply a problem that another container is probably running at the same time. Can you confirm by running `docker ps`? And then you can stop running containers manually with `docker --stop <containerid>`.

**Comment by regisb** [comment]
@frohro Yes, please open a new issue so that we don't bother @roblhibbard with useless notifications :)
When you create the new issue, please make sure to stop *all* remaining containers before restarting.
