### ISSUE TITLE
K8s Error: Course import or export 

### ISSUE THREAD

**Issue by aeikman** [regisb/tutor#124]
## Steps to reproduce

Run K8 on gcp.  Course Import fails in unpacking stage. Course export fails in Exporting stage. 

From kubernetes log:

```
2019-01-14 01:36:39,718 INFO 10 [contentstore.views.import_export] import_export.py:201 - Course import course-v1:els+1+1: Upload complete
2019-01-14 01:36:40,495 INFO 10 [contentstore.views.import_export] import_export.py:213 - Course import course-v1:els+1+1: Temp data cleared
2019-01-14 01:36:40,496 ERROR 10 [contentstore.views.import_export] import_export.py:216 - error importing course
Traceback (most recent call last):
  File "/openedx/edx-platform/cms/djangoapps/contentstore/views/import_export.py", line 206, in _write_chunk
    request.user.id, text_type(courselike_key), storage_path, filename, request.LANGUAGE_CODE)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 461, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 573, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 354, in send_task
    reply_to=reply_to or self.oid, **options
  File "/usr/local/lib/python2.7/dist-packages/celery/app/amqp.py", line 310, in publish_task
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/kombu/messaging.py", line 172, in publish
    routing_key, mandatory, immediate, exchange, declare)
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 470, in _ensured
    interval_max)
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 382, in ensure_connection
    interval_start, interval_step, interval_max, callback)
  File "/usr/local/lib/python2.7/dist-packages/kombu/utils/__init__.py", line 246, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 250, in connect
    return self.connection
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 756, in connection
    self._connection = self._establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 711, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
    conn = self.Connection(**opts)
  File "/usr/local/lib/python2.7/dist-packages/amqp/connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "/usr/local/lib/python2.7/dist-packages/amqp/connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "/usr/local/lib/python2.7/dist-packages/amqp/transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/usr/local/lib/python2.7/dist-packages/amqp/transport.py", line 75, in __init__
    socket.SOCK_STREAM, SOL_TCP):
gaierror: [Errno -2] Name or service not known
```
data/lms/logs is empty.

```
make: Nothing to be done for 'cms'.
make: *** No rule to make target 'info'.  Stop.
```

Theses error do not appear when running locally.

**Comment by regisb** [comment]
Hi @aeikman! This is due to the fact that rabbitmq is not running. I'm working on a fix.

**Comment by regisb** [comment]
Please run the following commands:

```
git pull
make upgrade
```

Once rabbitmq has booted (visible in the dashboard), run the `demo-course` command again.

Can you please confirm that this solves your issue?
