### ISSUE TITLE
forum container keeps restarting

### ISSUE THREAD

**Issue by kbitr** [regisb/tutor#137]
## Steps to reproduce

Coming from older tutor. git pull. make all/make run/make daemon.

## Unexpected behavior

```
make all
make[1]: Verzeichnis „/root/docker/tutor/deploy/local“ wird betreten
make[1]: Verzeichnis „/root/docker/tutor/deploy/local“ wird verlassen
make[1]: Verzeichnis „/root/docker/tutor/deploy/local“ wird betreten
make[1]: Verzeichnis „/root/docker/tutor/deploy/local“ wird verlassen
make[1]: Verzeichnis „/root/docker/tutor/deploy/local“ wird betreten
docker-compose pull
Pulling memcached      ... done
Pulling mongodb        ... done
Pulling mysql          ... done
Pulling elasticsearch  ... done
Pulling openedx-assets ... done
Pulling rabbitmq       ... done
Pulling smtp           ... done
Pulling forum          ... done
Pulling lms            ... done
Pulling cms            ... done
Pulling lms_worker     ... done
Pulling cms_worker     ... done
Pulling notes          ... done
Pulling nginx          ... done
make[1]: Verzeichnis „/root/docker/tutor/deploy/local“ wird verlassen
make[1]: Verzeichnis „/root/docker/tutor/deploy/local“ wird betreten
docker-compose up -d mysql
Starting local_mysql_1_651bbbc60e33 ... done
sleep 30;
docker-compose stop mysql
Stopping local_mysql_1_651bbbc60e33 ... done
docker-compose run --rm -v $(pwd)/../env/openedx/scripts:/openedx/scripts lms /openedx/scripts/provision.sh
Starting local_smtp_1_cf56e100c363          ... done
Starting local_mongodb_1_25ecd9f399bb       ... done
Starting local_rabbitmq_1_5282bb2312b8      ... done
Starting local_memcached_1_9330277ffcc2     ... done
Starting local_elasticsearch_1_a1d504d438d8 ... done
Starting local_mysql_1_651bbbc60e33         ... done
Starting local_forum_1_9e7f73e2a716         ... done
2019/01/25 18:03:13 Waiting for: tcp://mysql:3306
2019/01/25 18:03:13 Connected to tcp://mysql:3306
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
Starting local_mysql_1_651bbbc60e33         ... done
Starting local_memcached_1_9330277ffcc2     ... done
Starting local_rabbitmq_1_5282bb2312b8      ... done
Starting local_mongodb_1_25ecd9f399bb       ... done
Starting local_elasticsearch_1_a1d504d438d8 ... done
Starting local_forum_1_9e7f73e2a716         ... done
2019/01/25 18:03:15 Waiting for: tcp://mysql:3306
2019/01/25 18:03:15 Connected to tcp://mysql:3306
System check identified some issues:

WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'
	HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode
Operations to perform:
  Apply all migrations: admin, api_admin, assessment, auth, badges, block_structure, bookmarks, branding, bulk_email, catalog, celery_utils, certificates, commerce, completion, consent, contentserver, contenttypes, cors_csrf, course_action_state, course_goals, course_groups, course_modes, course_overviews, course_structures, courseware, crawlers, credentials, credit, dark_lang, database_fixups, degreed, django_comment_common, django_notify, django_openid_auth, djcelery, edx_oauth2_provider, edx_proctoring, edxval, email_marketing, embargo, enterprise, entitlements, experiments, external_auth, grades, instructor_task, integrated_channel, lms_xblock, microsite_configuration, milestones, mobile_api, notes, oauth2, oauth2_provider, oauth_dispatch, oauth_provider, organizations, programs, redirects, rss_proxy, sap_success_factors, schedules, self_paced, sessions, shoppingcart, site_configuration, sites, social_django, splash, static_replace, status, student, submissions, survey, teams, theming, third_party_auth, track, user_api, util, verified_track_content, verify_student, video_config, video_pipeline, waffle, waffle_utils, wiki, workflow, xblock_django
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Starting local_smtp_1_cf56e100c363      ... done
Starting local_mysql_1_651bbbc60e33     ... done
Starting local_memcached_1_9330277ffcc2 ... done
Starting local_mongodb_1_25ecd9f399bb   ... done
2019/01/25 18:03:31 Waiting for: tcp://mysql:3306
2019/01/25 18:03:31 Connected to tcp://mysql:3306
System check identified some issues:

WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'
	HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode
Operations to perform:
  Apply all migrations: admin, api_admin, assessment, auth, block_structure, bookmarks, catalog, celery_utils, completion, consent, contentserver, contentstore, contenttypes, course_action_state, course_creators, course_groups, course_modes, course_overviews, course_structures, courseware, crawlers, credit, dark_lang, database_fixups, degreed, django_comment_common, django_notify, django_openid_auth, djcelery, edx_oauth2_provider, edx_proctoring, edxval, embargo, enterprise, entitlements, external_auth, integrated_channel, microsite_configuration, milestones, oauth2, oauth2_provider, oauth_provider, organizations, redirects, sap_success_factors, schedules, self_paced, sessions, site_configuration, sites, static_replace, student, submissions, survey, tagging, theming, track, user_api, user_tasks, verified_track_content, verify_student, video_config, video_pipeline, waffle, waffle_utils, wiki, workflow, xblock_config, xblock_django
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
make reindex-courses
Starting local_mongodb_1_25ecd9f399bb   ... 
Starting local_mysql_1_651bbbc60e33     ... done
Starting local_smtp_1_cf56e100c363      ... done
Starting local_mongodb_1_25ecd9f399bb   ... done
Starting local_rabbitmq_1_5282bb2312b8  ... done
2019-01-25 18:03:51,914 INFO 1 [elasticsearch] base.py:63 - HEAD http://elasticsearch:9200/courseware_index [status:200 request:0.005s]
No handlers could be found for logger "elasticsearch.trace"
2019-01-25 18:03:51,916 INFO 1 [elasticsearch] base.py:63 - HEAD http://elasticsearch:9200/courseware_index [status:200 request:0.003s]
2019-01-25 18:03:51,919 INFO 1 [elasticsearch] base.py:63 - HEAD http://elasticsearch:9200/courseware_index/courseware_content [status:200 request:0.002s]
2019-01-25 18:03:51,924 INFO 1 [elasticsearch] base.py:63 - GET http://elasticsearch:9200/courseware_index/_mapping/courseware_content [status:200 request:0.005s]
make[2]: Verzeichnis „/root/docker/tutor/deploy/local“ wird verlassen
docker-compose run --rm forum bash -c "bundle exec rake search:initialize && \
	bundle exec rake search:rebuild_index"
Starting local_elasticsearch_1_a1d504d438d8 ... done
Starting local_mongodb_1_25ecd9f399bb       ... done
/openedx/cs_comments_service/lib/tasks/kpis.rake:7: warning: already initialized constant ROOT
/openedx/cs_comments_service/lib/tasks/deep_search.rake:7: warning: previous definition of ROOT was here
/openedx/cs_comments_service/lib/tasks/flags.rake:6: warning: already initialized constant ROOT
/openedx/cs_comments_service/lib/tasks/kpis.rake:7: warning: previous definition of ROOT was here
W, [2019-01-25T18:03:56.455047 #6]  WARN -- : NewRelic agent library not installed
/openedx/cs_comments_service/vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/base.rb:52: warning: constant ::Fixnum is deprecated
/openedx/cs_comments_service/vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/base.rb:54: warning: constant ::Fixnum is deprecated
/openedx/cs_comments_service/models/constants.rb:2: warning: already initialized constant COURSE_ID
/openedx/cs_comments_service/lib/tasks/db.rake:28: warning: previous definition of COURSE_ID was here
W, [2019-01-25T18:03:57.075559 #6]  WARN -- : Overwriting existing field _id in class User.
W, [2019-01-25T18:03:57.101259 #6]  WARN -- : MONGODB | Unsupported client option 'max_retries'. It will be ignored.
W, [2019-01-25T18:03:57.101372 #6]  WARN -- : MONGODB | Unsupported client option 'retry_interval'. It will be ignored.
W, [2019-01-25T18:03:57.101423 #6]  WARN -- : MONGODB | Unsupported client option 'timeout'. It will be ignored.
W, [2019-01-25T18:03:57.107290 #6]  WARN -- : NewRelic agent library not installed
I, [2019-01-25T18:03:57.110979 #6]  INFO -- : Skipping initialization. The 'content' alias already exists. If 'rake search:validate_index' indicates a problem with the mappings, you could either use 'rake search:rebuild_index' to reload from the db or 'rake search:initialize[true]' to force initialization with an empty index.
/openedx/cs_comments_service/lib/tasks/kpis.rake:7: warning: already initialized constant ROOT
/openedx/cs_comments_service/lib/tasks/deep_search.rake:7: warning: previous definition of ROOT was here
/openedx/cs_comments_service/lib/tasks/flags.rake:6: warning: already initialized constant ROOT
/openedx/cs_comments_service/lib/tasks/kpis.rake:7: warning: previous definition of ROOT was here
W, [2019-01-25T18:03:59.325591 #1]  WARN -- : NewRelic agent library not installed
/openedx/cs_comments_service/vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/base.rb:52: warning: constant ::Fixnum is deprecated
/openedx/cs_comments_service/vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/base.rb:54: warning: constant ::Fixnum is deprecated
/openedx/cs_comments_service/models/constants.rb:2: warning: already initialized constant COURSE_ID
/openedx/cs_comments_service/lib/tasks/db.rake:28: warning: previous definition of COURSE_ID was here
W, [2019-01-25T18:03:59.881549 #1]  WARN -- : Overwriting existing field _id in class User.
W, [2019-01-25T18:03:59.898953 #1]  WARN -- : MONGODB | Unsupported client option 'max_retries'. It will be ignored.
W, [2019-01-25T18:03:59.899077 #1]  WARN -- : MONGODB | Unsupported client option 'retry_interval'. It will be ignored.
W, [2019-01-25T18:03:59.899118 #1]  WARN -- : MONGODB | Unsupported client option 'timeout'. It will be ignored.
W, [2019-01-25T18:03:59.904789 #1]  WARN -- : NewRelic agent library not installed
I, [2019-01-25T18:04:00.006456 #1]  INFO -- : Added mappings to index: content_20190125180359905.
I, [2019-01-25T18:04:00.006739 #1]  INFO -- : Created new index: content_20190125180359905.
I, [2019-01-25T18:04:00.106050 #1]  INFO -- : Imported batch 1 into the index
I, [2019-01-25T18:04:00.117769 #1]  INFO -- : Catch up from 2019-01-25 17:58:59 UTC complete.
I, [2019-01-25T18:04:00.143618 #1]  INFO -- : Alias [content] now points to index [content_20190125180359905].
I, [2019-01-25T18:04:00.153040 #1]  INFO -- : Catch up from 2019-01-25 17:59:00 UTC complete.
I, [2019-01-25T18:04:00.153129 #1]  INFO -- : Rebuild index complete.
make[2]: Verzeichnis „/root/docker/tutor/deploy/local“ wird betreten
docker-compose run --rm notes ./manage.py migrate
Starting local_mysql_1_651bbbc60e33 ... done
System check identified some issues:

WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'
	HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode
Operations to perform:
  Apply all migrations: auth, contenttypes, v1
Running migrations:
  No migrations to apply.
make[2]: Verzeichnis „/root/docker/tutor/deploy/local“ wird verlassen
Starting local_rabbitmq_1_5282bb2312b8      ... done
Starting local_elasticsearch_1_a1d504d438d8 ... done
Starting local_mongodb_1_25ecd9f399bb       ... done
Starting local_memcached_1_9330277ffcc2     ... done
Starting local_mysql_1_651bbbc60e33         ... done
Starting local_forum_1_9e7f73e2a716         ... done
Found existing user: "notes"
Adding user "notes" to groups []
Removing user "notes" from groups []
{
    "name": "edx-notes", 
    "url": "http://notes.openedx:8000", 
    "logout_uri": "http://notes.openedx:8000/logout/", 
    "redirect_uri": "http://notes.openedx:8000/complete/edx-oidc/", 
    "client_id": "notes", 
    "user": {
        "username": "notes", 
        "first_name": "", 
        "last_name": "", 
        "is_active": true, 
        "email": "notes@courses.it.digifom.com", 
        "is_superuser": true, 
        "is_staff": true, 
        "last_login": null, 
        "password": "pbkdf2_sha256$36000$XRDqHfhN87mO$IM6BPTU4RHeq66eE1svSPEbJgDqjMIUPq+p8+q+dq+g=", 
        "id": 2, 
        "date_joined": "2019-01-05T13:04:06.275Z"
    }, 
    "client_type": 0, 
    "client_secret": "reE2jZlSSlSkK4NavCuXItzH"
}
make[1]: Verzeichnis „/root/docker/tutor/deploy/local“ wird verlassen
make[1]: Verzeichnis „/root/docker/tutor/deploy/local“ wird betreten
docker-compose up -d
local_mongodb_1_25ecd9f399bb is up-to-date
local_memcached_1_9330277ffcc2 is up-to-date
local_rabbitmq_1_5282bb2312b8 is up-to-date
Starting local_openedx-assets_1_78f0ff29a9fd ... 
local_smtp_1_cf56e100c363 is up-to-date
local_elasticsearch_1_a1d504d438d8 is up-to-date
local_mysql_1_651bbbc60e33 is up-to-date
Starting local_openedx-assets_1_78f0ff29a9fd ... done
Starting local_notes_1_bacb7b1f9a9a          ... done
Starting local_cms_1_8ec65621ba50            ... done
Starting local_lms_1_39143639ff8d            ... done
Starting local_cms_worker_1_9ebb34c51af9     ... done
Starting local_nginx_1_4989a4e975cd          ... done
Starting local_lms_worker_1_16fe666ed918     ... done
Daemon is up and running
make[1]: Verzeichnis „/root/docker/tutor/deploy/local“ wird verlassen
All set \o/ You can access the LMS at http://localhost and the CMS at http://studio.localhost
root@v22019017578180573:~/docker/tutor/deploy/local# docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS                          PORTS                                      NAMES
c4e65ca9a198        nginx:1.13                               "nginx -g 'daemon of…"   15 minutes ago      Up 3 seconds                    80/tcp                                     local_nginx_1_4989a4e975cd
f38913b9087e        regis/openedx:hawthorn                   "docker-entrypoint.s…"   15 minutes ago      Up 4 seconds                    8000/tcp                                   local_cms_worker_1_9ebb34c51af9
f1a827c99489        regis/openedx:hawthorn                   "docker-entrypoint.s…"   15 minutes ago      Up 2 seconds                    8000/tcp                                   local_lms_worker_1_16fe666ed918
516fe23931fa        regis/openedx:hawthorn                   "docker-entrypoint.s…"   15 minutes ago      Up 5 seconds                    8000/tcp                                   local_cms_1_8ec65621ba50
49c0bbc9cd18        regis/openedx:hawthorn                   "docker-entrypoint.s…"   15 minutes ago      Up 4 seconds                    8000/tcp                                   local_lms_1_39143639ff8d
8794a407c787        regis/openedx-forum:hawthorn             "/bin/sh -c './bin/u…"   15 minutes ago      Restarting (1) 20 seconds ago                                              local_forum_1_9e7f73e2a716
14cbad84be3d        regis/openedx-notes:hawthorn             "/bin/sh -c 'gunicor…"   15 minutes ago      Up 6 seconds                    8000/tcp                                   local_notes_1_bacb7b1f9a9a
032681afd83e        rabbitmq:3.6.10                          "docker-entrypoint.s…"   15 minutes ago      Up About a minute               4369/tcp, 5671-5672/tcp, 25672/tcp         local_rabbitmq_1_5282bb2312b8
ef87c4de786d        memcached:1.4.38                         "docker-entrypoint.s…"   15 minutes ago      Up About a minute               11211/tcp                                  local_memcached_1_9330277ffcc2
5776be339f47        elasticsearch:1.5.2                      "/docker-entrypoint.…"   15 minutes ago      Up About a minute               9200/tcp, 9300/tcp                         local_elasticsearch_1_a1d504d438d8
4156aceaf4b0        mysql:5.6.36                             "docker-entrypoint.s…"   15 minutes ago      Up About a minute               3306/tcp                                   local_mysql_1_651bbbc60e33
e80b56fa515c        namshi/smtp                              "/bin/entrypoint.sh …"   15 minutes ago      Up About a minute               25/tcp                                     local_smtp_1_cf56e100c363
ca6ad0460cd9        mongo:3.2.16                             "docker-entrypoint.s…"   15 minutes ago      Up About a minute               27017/tcp                                  local_mongodb_1_25ecd9f399bb
```
## Additional info (IMPORTANT)

Log of forum container: 
```
W, [2019-01-25T18:06:34.408294 #6]  WARN -- : NewRelic agent library not installed
/openedx/cs_comments_service/vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/base.rb:52: warning: constant ::Fixnum is deprecated
/openedx/cs_comments_service/vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/base.rb:54: warning: constant ::Fixnum is deprecated
W, [2019-01-25T18:06:34.687944 #6]  WARN -- : Overwriting existing field _id in class User.
W, [2019-01-25T18:06:34.705696 #6]  WARN -- : MONGODB | Unsupported client option 'max_retries'. It will be ignored.
W, [2019-01-25T18:06:34.705815 #6]  WARN -- : MONGODB | Unsupported client option 'retry_interval'. It will be ignored.
W, [2019-01-25T18:06:34.705843 #6]  WARN -- : MONGODB | Unsupported client option 'timeout'. It will be ignored.
W, [2019-01-25T18:06:34.711125 #6]  WARN -- : NewRelic agent library not installed
I, [2019-01-25T18:06:34.721074 #6]  INFO -- : Passed: Alias 'content' exists with up-to-date mappings.
/openedx/cs_comments_service/vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:7 (or pid=/tmp/forum_unicorn.pid is stale) (ArgumentError)
	from /openedx/cs_comments_service/vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:137:in `start'
	from /openedx/cs_comments_service/vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.0/bin/unicorn:126:in `<top (required)>'
	from ./bin/unicorn:16:in `load'
	from ./bin/unicorn:16:in `<main>'
W, [2019-01-25T18:07:37.546824 #6]  WARN -- : NewRelic agent library not installed
/openedx/cs_comments_service/vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/base.rb:52: warning: constant ::Fixnum is deprecated
/openedx/cs_comments_service/vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/base.rb:54: warning: constant ::Fixnum is deprecated
W, [2019-01-25T18:07:37.812675 #6]  WARN -- : Overwriting existing field _id in class User.
W, [2019-01-25T18:07:37.839521 #6]  WARN -- : MONGODB | Unsupported client option 'max_retries'. It will be ignored.
W, [2019-01-25T18:07:37.839657 #6]  WARN -- : MONGODB | Unsupported client option 'retry_interval'. It will be ignored.
W, [2019-01-25T18:07:37.839702 #6]  WARN -- : MONGODB | Unsupported client option 'timeout'. It will be ignored.
W, [2019-01-25T18:07:37.845005 #6]  WARN -- : NewRelic agent library not installed
I, [2019-01-25T18:07:37.857443 #6]  INFO -- : Passed: Alias 'content' exists with up-to-date mappings.
/openedx/cs_comments_service/vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:7 (or pid=/tmp/forum_unicorn.pid is stale) (ArgumentError)
	from /openedx/cs_comments_service/vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:137:in `start'
	from /openedx/cs_comments_service/vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.0/bin/unicorn:126:in `<top (required)>'
	from ./bin/unicorn:16:in `load'
	from ./bin/unicorn:16:in `<main>'
W, [2019-01-25T18:08:40.850974 #6]  WARN -- : NewRelic agent library not installed
/openedx/cs_comments_service/vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/base.rb:52: warning: constant ::Fixnum is deprecated
/openedx/cs_comments_service/vendor/bundle/ruby/2.4.0/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/base.rb:54: warning: constant ::Fixnum is deprecated
W, [2019-01-25T18:08:41.138366 #6]  WARN -- : Overwriting existing field _id in class User.
W, [2019-01-25T18:08:41.166156 #6]  WARN -- : MONGODB | Unsupported client option 'max_retries'. It will be ignored.
W, [2019-01-25T18:08:41.166288 #6]  WARN -- : MONGODB | Unsupported client option 'retry_interval'. It will be ignored.
W, [2019-01-25T18:08:41.166340 #6]  WARN -- : MONGODB | Unsupported client option 'timeout'. It will be ignored.
W, [2019-01-25T18:08:41.172134 #6]  WARN -- : NewRelic agent library not installed
I, [2019-01-25T18:08:41.184195 #6]  INFO -- : Passed: Alias 'content' exists with up-to-date mappings.
/openedx/cs_comments_service/vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:7 (or pid=/tmp/forum_unicorn.pid is stale) (ArgumentError)
	from /openedx/cs_comments_service/vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.0/lib/unicorn/http_server.rb:137:in `start'
	from /openedx/cs_comments_service/vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.0/bin/unicorn:126:in `<top (required)>'
	from ./bin/unicorn:16:in `load'
	from ./bin/unicorn:16:in `<main>'
```

edx is not reachable as 502 Bad Gateway

**Comment by kbitr** [comment]
@regisb: You can delete this issue. I have no idea why this happened and I cannot reproduce this issue.

**Comment by regisb** [comment]
:+1:
