### ISSUE TITLE
 Connection refused kubectl

### ISSUE THREAD

**Issue by nikhilrayaprolu** [regisb/tutor#146]
## Steps to reproduce

`make all` in kubernetes. I am trying to deploy kubernetes on Gcloud and faced this issue. Every thing till database migrations went well, except the reindexing of a course.

## Unexpected behavior

```
kubectl exec -n openedx -it $(kubectl get pods -n openedx --selector=app=cms -o name | head -1 | cut -d '/' -f 2) -- ./manage.py cms reindex_course --all --setup
Traceback (most recent call last):
  File "./manage.py", line 121, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/openedx/edx-platform/cms/djangoapps/contentstore/management/commands/reindex_course.py", line 68, in handle
    store = modulestore()
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 321, in modulestore
    settings.MODULESTORE['default'].get('OPTIONS', {})
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 303, in create_modulestore_instance
    **_options
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/modulestore/mixed.py", line 176, in __init__
    signal_handler=signal_handler,
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 303, in create_modulestore_instance
    **_options
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/split.py", line 707, in __init__
    self.db_connection = MongoConnection(**doc_store_config)
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/modulestore/split_mongo/mongo_connection.py", line 300, in __init__
    retry_wait_time=retry_wait_time, **kwargs
  File "/openedx/edx-platform/common/lib/xmodule/xmodule/mongo_utils.py", line 50, in connect_to_mongodb
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 425, in __init__
    raise ConnectionFailure(str(e))
pymongo.errors.ConnectionFailure: [Errno 111] Connection refused
command terminated with exit code 1
```

**Comment by regisb** [comment]
1. Is the mongodb service up? 
2. Please try again after some time by running `make reindex-courses`.

**Comment by regisb** [comment]
looks like I somehow forgot to include the `elasticsearch` service in Kubernetes :sweat_smile: This will be fixed in thenext release I'm currently working on.

**Comment by nikhilrayaprolu** [comment]
Ohh, I had internal exams at my university till today so couldn't check my deployment to reply you. But thanks a lot for the quick replies, and quick fixes. 😅

I think this issue can be closed now with the new release? 
I will try again deploying the newer tutor and let you know about the status.

**Comment by nikhilrayaprolu** [comment]
By the way, I have seen that you updated the tutor to a python package, does this mean if I make any source code changes to tutor, I have to reinstall the package (let's say while developing a new feature to tutor)? Or can I run a python package without installing it?

**Comment by regisb** [comment]
> I think this issue can be closed now as the new release made?

Yes, absolutely! The issue was related to incorrect settings.

> By the way, I have seen that you updated the tutor to a python package, does this mean if I make any source code changes to tutor, I have to reinstall the package (let's say while developing a new feature to tutor)? Or can I run a python package without installing it?

Yes, this is a major upgrade. While using normally tutor, you don't need to re-install. Just download the binary from the releases page: https://github.com/regisb/tutor/releases/

However, when developing Tutor, you should install tutor in development mode:

    python setup.py develop

Happy coding!
