### ISSUE TITLE
Hawthorn installation fails halfway through

### ISSUE THREAD

**Issue by ProtoBrunch** [regisb/tutor#195]
Hello

We recently tried setting up a new Platform with the Hawthorn-version of the openedx-images.
To do that we added the following lines to the config.yml:

```
DOCKER_IMAGE_OPENEDX: regis/openedx:hawthorn
DOCKER_IMAGE_ANDROID: regis/openedx:hawthorn
DOCKER_IMAGE_FORUM: regis/openedx:hawthorn
DOCKER_IMAGE_NOTES: regis/openedx:hawthorn
DOCKER_IMAGE_XQUEUE: regis/openedx:hawthorn
```

We then started the process with `tutor local quickstart` and went through the process as usual.

During the DB-migration process the following error popped up and the process stopped:

```
Running lms migrations...
Starting tutor_local_smtp_1  ...
Starting tutor_local_smtp_1          ... done
Starting tutor_local_mysql_1 ...
Starting tutor_local_elasticsearch_1 ... done
Starting tutor_local_memcached_1     ... done
Starting tutor_local_rabbitmq_1      ... done
Starting tutor_local_mongodb_1       ... done
Starting tutor_local_forum_1         ... done
2019/04/10 08:50:27 Waiting for: tcp://mysql:3306
2019/04/10 08:50:27 Connected to tcp://mysql:3306
Traceback (most recent call last):
  File "./manage.py", line 117, in <module>
    startup = importlib.import_module(edx_args.startup)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/openedx/edx-platform/lms/startup.py", line 9, in <module>
    settings.INSTALLED_APPS  # pylint: disable=pointless-statement
  File "/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/openedx/edx-platform/lms/envs/tutor/production.py", line 2, in <module>
    from lms.envs.production import *
ImportError: No module named production
Error: Command failed with status 1: docker-compose -f /home/EdxTestServerAdmin/.local/share/tutor/env/local/docker-compose.yml --project-name tutor_local run --rm lms bash -e -c dockerize -wait tcp://mysql:3306 -timeout 20s && ./manage.py lms migrate
```

**Comment by travlr** [comment]
Hi @ProtoBrunch .. which version of tutor are you using.. I think you need to use a version <= v3.2.2 inorder to work with Hawthorn and not Ironwood.

**Comment by regisb** [comment]
Indeed, Hawthorn was only supported until v3.3.0. The current tutor release is not backward compatible with older Open edX releases. So, in order to run Hawthorn, you will have to download an older release of Tutor: https://github.com/regisb/tutor/releases/tag/v3.2.2

May I ask what is the backstory here? Why are you trying to run Hawthorn? I'd like to better understand your requirements.
